### ISSUE TITLE
Code for fig 4.11 does not work.

### ISSUE THREAD

**Issue by suneecat** [PacktPublishing/Django-4-for-the-Impatient#2]
The code as described for Figure 4.11 in the text does not work as claimed.

Instead of displaying "Searching for star wars", it always displays "Searching for searchTerm"

**Comment by danielgara** [comment]
Hi @suneecat can you send as an screenshot of your movie/views.py file, and your movie/templates/home.html file (to try to find the error)?

Thanks!

**Comment by suneecat** [comment]
Hello @danielgara 

The files I am using have been copied from github.

Here is a snap of the movie/views.py file:
![views_py](https://user-images.githubusercontent.com/6851656/227751720-53250355-73a9-449f-8c61-cbc86f74ccdf.PNG)

Here is a snap of the movie/templates/home.html file:
![home_html](https://user-images.githubusercontent.com/6851656/227752008-489a8bbb-332e-49ed-9566-fbcd4d4a8333.PNG)

**Comment by suneecat** [comment]
Thanks.

**Comment by shruthis-shetty** [comment]
Hello @suneecat ,
I hope your issue got resolved. Please reply so that I will close the issue asap.

**Comment by shruthis-shetty** [comment]
Hello @suneecat ,
I hope your issue got resolved. Please reply so that I will close the issue asap.

**Comment by shruthis-shetty** [comment]
Hello @suneecat ,
I hope your issue got resolved. Please reply so that I will close the issue asap.

**Comment by danielgara** [comment]
@suneecat the code looks good to me. Maybe if it doesn't work, you could try to upload the entire project code in a zip file and share it with us to take a look.

**Comment by danielgara** [comment]
@suneecat the code looks good to me. Maybe if it doesn't work, you could try to upload the entire project code in a zip file and share it with us to take a look.

**Comment by suneecat** [comment]
Hello @danielgara 

I have copied all the code from the Chapter04 github page and it now works.

As I progressed through chapter 4 it looks like I left unneeded lines in some of the code.

This issue can be closed.
Thanks for your help.

**Comment by suneecat** [comment]
I double checked all the code and made sure it matches what is on the
github page for Chapter04.
The code now works.
As I proceed through chapter 4, I left some unneeded lines in certain code
sections when making edits, so the code was "short circuited".

This issue can be closed.

Thanks for your help.

**Comment by suneecat** [comment]
The issue can be closed.
