### ISSUE TITLE
Images and movie title not showing up in card

### ISSUE THREAD

**Issue by abdulious3** [PacktPublishing/Django-4-for-the-Impatient#3]
![Screenshot 2023-05-04 093454](https://user-images.githubusercontent.com/25130315/236268144-6026c358-86b1-42a6-b8b1-e6bf7df6bc2b.png)

**Comment by abdulious3** [comment]
I'm in chapter 6.  Here is my code:
moviereviews/settings.py:
at bottom:
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

at top:
import os
from pathlib import Path

**Comment by abdulious3** [comment]
here is my home.html:
   <p>Searching for: {{ searchTerm }}</p>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for movie in movies %}
            <div v-for="movie in movies" class="col">
              <div class="card">
                <img class="card-img-top" src="{{ 
                  movie.image.url }}">
                <div class="card-body">
                  <h5 class="card-title fw-bold">{{ movie.title
                    }}</h5>
                  <p class="card-text">{{ movie.description
                  }}</p>
                  {% if movie.url %}
                  <a href="{{ movie.url }}"
                    class="btn btn-primary">
                    Movie Link
                  </a>
                  {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>

**Comment by danielgara** [comment]
Hi @abdulious3, can you upload your complete project code to a new GitHub repository, and that way we could take a look of it?

Or maybe to Google Drive or something. Let us know, have a great day!

**Comment by abdulious3** [comment]
Yes I will. Thanks

**Comment by abdulious3** [comment]
Hello. I made a moviereviewsproject repository. I still am working on how to share it. I'm still new to github. Thanks

**Comment by abdulious3** [comment]
> Hi @abdulious3, can you upload your complete project code to a new GitHub repository, and that way we could take a look of it?
> 
> Or maybe to Google Drive or something. Let us know, have a great day!

Hello. I made a moviereviewsproject repository. I still am working on how to share it. I'm still new to github. Thanks

**Comment by abdulious3** [comment]
> Hi @abdulious3, can you upload your complete project code to a new GitHub repository, and that way we could take a look of it?
> 
> Or maybe to Google Drive or something. Let us know, have a great day!

Here is the link to the repository: https://github.com/abdulious3/moviereviewsproject Thanks for your help.

**Comment by abdulious3** [comment]
> Hi @abdulious3, can you upload your complete project code to a new GitHub repository, and that way we could take a look of it?
> 
> Or maybe to Google Drive or something. Let us know, have a great day!

I fixed the issue. I had some brackets on a new line. I just had to adjust that and now everything is working.

**Comment by danielgara** [comment]
@abdulious3 exactly, I was testing your code, and that was the problem. Have a great day!

**Comment by abdulious3** [comment]
Thanks for your help!
